### ISSUE TITLE
Warning: entry point could not be loaded. Contact its author for help

### ISSUE THREAD

**Issue by sr67** [serycjon/vpype-flow-imager#17]
vpype --version
vpype 1.10.0

pipx inject vpype git+https://github.com/serycjon/vpype-flow-imager
  injected package vpype-flow-imager into venv vpype
done! 

vpype --help
...
Unknown:
    vpype_flow_imager  † Warning: could not load plugin. See `vpype
                       vpype_flow_imager --help`.

vpype vpype_flow_imager --help

Warning: entry point could not be loaded. Contact its author for help.

ImportError: ~/.local/pipx/venvs/vpype/lib/python3.9/site-packages/hnswlib.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

**Comment by serycjon** [comment]
Hi, thanks for the report.  Seems like the hnswlib dependency was compiled incorrectly. I have added a fallback option (will draw with the `-kdt` parameter).  It will work slower, but will be more precise. Try to update the package and let me know if it works.
```
pipx upgrade vpype --include-injected
```
should do the upgrade in your case.

(feel free to comment / reopen the issue here)

**Comment by sr67** [comment]
Thanks! Error is gone and seems to be loading. Looking forward to trying it out.
