### ISSUE TITLE
DPI - Image Resolution ignored?

### ISSUE THREAD

**Issue by krummrey** [serycjon/vpype-flow-imager#21]
Increasing the image size in pixels does **not** increase the resolution of the svg output. The output is just scaled up to match the size of the larger image.

That way the density of the image varies and does not stay constant related to an images dpi.
I would expect a 800x800px image at 72 dpi to have the same level of blackness as a 1200x1200 image with the same 72 dpi. 
Now the larger image gets lighter as the same amount of lines are drawn regardless of the numbers of pixels in the image or it's dpi value.

Current situation
<img width="642" alt="Bildschirmfoto 2022-06-25 um 13 46 31" src="https://user-images.githubusercontent.com/4517632/175772268-88bbeb56-483c-40d1-aecf-046f144a982a.png">

Hack with adjusting line separation
<img width="641" alt="Bildschirmfoto 2022-06-25 um 13 47 52" src="https://user-images.githubusercontent.com/4517632/175772290-3ac38936-aa65-4931-a544-403548c33224.png">

Proposed behavior. Calculate line separation based on dpi and lines per inch/mm. 
Or apply --max_size to the native resolution by default.

**Comment by serycjon** [comment]
Hi, this should be controlled by the `--max_size` parameter. Did you try changing that instead of hacking the `-ms` and `-Ms`. I think running the 400x400 image with `--max_size 400` and the 1600x1600 with `--max_size 1600` should work.

I am inclined to keep the default `max_size` fixed, not to surprise people with super long computation times when they try to input big images.  Also when you target the same output size, keeping the `max_size` fixed is probably the preferred variant - when you resize the outputs in your first image to be of the same size in all three cases (e.g. always plotting on A4 paper), the density should be the same.

What do you think?

**Comment by krummrey** [comment]
Yes, both methods work for me. I just find it counter intuitive to get basically the same result no matter what image size I start with. But that might just be me.
