### ISSUE TITLE
Get rid of opencv dependency

### ISSUE THREAD

**Issue by serycjon** [serycjon/vpype-flow-imager#7]
We only use imread, Canny, blur, GaussianBlur, cvtColor and resize.  Getting rid of opencv would make installation / docker images much smaller. Or would it?
```
25M     ./opencv_python_headless.libs
30M     ./scipy.libs
33M     ./numpy.libs
35M     ./matplotlib
61M     ./scipy
69M     ./cv2
78M     ./llvmlite
110M    ./skimage
446M    ./PySide2
```

**Comment by tnwei** [comment]
Hmm, you'd need either OpenCV or scikit-image to do Canny edge detection, and currently skimage isn't used within this codebase. Personally wouldn't recommend switching though, since the functions aren't implemented one-to-one (ref: [Why is Gaussian Filter different between cv2 and skimage?](https://stackoverflow.com/questions/36263738/why-is-gaussian-filter-different-between-cv2-and-skimage)
